# Generated by Django 4.0.3 on 2022-03-31 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_alter_task_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 17, 32, 30492), verbose_name='Дата и время'),
        ),
    ]
