# Generated by Django 4.0.3 on 2022-05-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_delete_sendemail_alter_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Сообщение сервера', 'verbose_name_plural': 'Сообщения сервера'},
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 12, 36, 25, 991196), verbose_name='Дата и время'),
        ),
    ]
